name: Testing Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    types: [opened, edited, reopened]
env:


jobs:
  testing:
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
      options: --user 1001
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Cahce deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Project dependencies install
        run: npm i --force
      - name: Run tests
        run: npm run cypress:ci
      - name: Save test report
        uses: actions/upload-artifact@v3
        with:
          path: mochawesome-report
          name: Test Report
      - name: Get test report
        uses: actions/download-artifact@v3
        with:
          name: Test Report





