name: Testing Workflow
on: workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: sitespeedio/webbrowsers:chrome-118.0-firefox-118.0-edge-117.0
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Project dependencies install
        run: npm i --force
      - name: Run tests
        run: npm run cypress:e2e

